app:
  datasource:
    jdbc-url: ENC(+60ZoQA9C3xIkGsLEvNWWEBSBFHOmOi47JKryyv6zjnHk90WFyZOmvHRN+etifuuZSaTviuNBcU=)
    username: ENC(1Kq0vluoQ1Vp3Fn9C5FCntojLhDnTtxd)
    password: ENC(3XI6tcCl9ss7+DZ9SeMExg==)
    pool-size: 3

#    todo: we need a different configuration for running locally.